import './globals.css'
import type { Metadata } from 'next'
// next/fontはGoogleFontsをホスティングすることでgoogleにアクセスせずにfontを利用するもの。
// import { Inter } from 'next/font/google'
import { Figtree } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
const font = Figtree({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const metadata: Metadata = {
  title: 'Spotify Clone YT',
  description: 'youtubeのtuto動画',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body className={font.className}>{children}</body>
    </html>
  )
}
